language: cpp

sudo: required
dist: trusty

notifications: 
  email:
    recipients:
    - rncbc@rncbc.org
    on_success: change
    on_failure: always

branches:
  only:
  - master

env:
- QT_SELECT=4
- QT_SELECT=5

before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- if [[ "$QT_SELECT" = "5" ]]; then sudo add-apt-repository --yes ppa:beineri/opt-qt592-trusty; fi
- sudo apt-get update -qq

install:
- if [[ "$QT_SELECT" = "4" ]]; then sudo apt-get install -qq libqt4-dev; fi
- if [[ "$QT_SELECT" = "5" ]]; then sudo apt-get install -qq qt59base qt59tools qt59x11extras; source /opt/qt*/bin/qt*-env.sh; fi
- sudo apt-get install -qq libjack-dev libasound2-dev libsndfile1-dev
- sudo apt-get install -qq libvorbis-dev libmad0-dev libsamplerate-dev zlib1g-dev
- sudo apt-get install -qq ladspa-sdk dssi-dev liblo-dev librubberband-dev
- sudo apt-get install -qq lv2-dev liblilv-dev libsuil-dev

before_script:
- git fetch --unshallow --tags -q
- ./autogen.sh

script:
- if [ "$QT_SELECT" = "4" ]; then ./configure --enable-qt4; fi
- if [ "$QT_SELECT" = "5" ]; then ./configure; fi
- make && sudo make install
